{% set name = "python-telegram-bot" %}
{% set version = "21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-telegram-bot-{{ version }}.tar.gz
  sha256: e42d5cfec69d64fd921a41ff56215f92a48b8ddb5500235798c2bd3d9eb7242e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - httpx >=0.27,<1.dev0

test:
  imports:
    - telegram

about:
  home: https://python-telegram-bot.org/
  license: LGPL-3.0-only AND GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - LICENSE.dual
    - LICENSE.lesser
  summary: We have made you a wrapper you can't refuse
  description: |
    This library provides a pure Python, asynchronous interface for the Telegram
    Bot API. It's compatible with Python versions 3.7+.
    In addition to the pure API implementation, this library features a number of
    high-level classes to make the development of bots easy and straightforward.
    These classes are contained in the telegram.ext submodule.  doc_url: https://python-telegram-bot.readthedocs.io/en/stable/
  dev_url: https://github.com/python-telegram-bot/python-telegram-bot

extra:
  recipe-maintainers:
    - xylar
    - mdraw
