{% set name = "python-telegram-bot" %}
{% set version = "12.4.1" %}
{% set sha256 = "f18a79e95c58add33fea9962fa027c580cf3bec01e3cd638930cc0baedc0c7a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - certifi
    - future >=0.16
    - tornado >=5.1
    - cryptography
    - decorator >=4.4.0
    # Optional:
    - ujson
    - pysocks

test:
  imports:
    - telegram
    - telegram.base
    - telegram.ext

about:
  home: https://github.com/python-telegram-bot/python-telegram-bot
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE.lesser
  summary: 'A pure Python interface for the Telegram Bot API.'

  description: |
    This library provides a pure Python interface for the Telegram Bot API.
    It's compatible with Python versions 2.7, 3.3+ and PyPy. It also works
    with Google App Engine.
    In addition to the pure API implementation, this library features a number
    of high-level classes to make the development of bots easy and
    straightforward. These classes are contained in the telegram.ext submodule.
  doc_url: https://python-telegram-bot.readthedocs.io/en/stable/
  dev_url: https://github.com/python-telegram-bot/python-telegram-bot

extra:
  recipe-maintainers:
    - mdraw
