{% set name = "python-telegram-bot" %}
{% set version = "13.12" %}
{% set sha256 = "daf55fb6f418b8752317fd12df824dd717e3229a87d83810a4cdd6e442f66de5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi
    - tornado >=6.1,<7
    - cryptography
    - apscheduler >=3.9.1,<3.10
    - cachetools >=5.1.0,<5.2
    - pytz >=2018.6
    - httpx >=0.23.0,<0.24    
    # Optional:
    - ujson
    - pysocks

test:
  imports:
    - telegram
    - telegram.base
    - telegram.ext

about:
  home: https://github.com/python-telegram-bot/python-telegram-bot
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE.lesser
  summary: A pure Python interface for the Telegram Bot API.

  description: |
    This library provides a pure Python interface for the Telegram Bot API.
    It's compatible with Python versions 2.7, 3.3+ and PyPy. It also works
    with Google App Engine.
    In addition to the pure API implementation, this library features a number
    of high-level classes to make the development of bots easy and
    straightforward. These classes are contained in the telegram.ext submodule.
  doc_url: https://python-telegram-bot.readthedocs.io/en/stable/
  dev_url: https://github.com/python-telegram-bot/python-telegram-bot

extra:
  recipe-maintainers:
    - mdraw
