{% set name = "python-telegram-bot" %}
{% set version = "22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: acf86f28d86d81cab736177d2988e5bcb27f2248137efd62e02c46e9ba1fe44c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.27,<1.dev0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - telegram
  commands:
    - pip check


about:
  home: https://python-telegram-bot.org/
  license: LGPL-3.0-only AND GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - LICENSE.dual
    - LICENSE.lesser
  summary: We have made you a wrapper you can't refuse
  description: |
    This library provides a pure Python, asynchronous interface for the Telegram
    Bot API. It's compatible with Python versions 3.7+.
    In addition to the pure API implementation, this library features a number of
    high-level classes to make the development of bots easy and straightforward.
    These classes are contained in the telegram.ext submodule.  doc_url: https://python-telegram-bot.readthedocs.io/en/stable/
  dev_url: https://github.com/python-telegram-bot/python-telegram-bot

extra:
  recipe-maintainers:
    - xylar
    - mdraw
